sources:
  - url: "https://www.labour.gov.in/static/uploads/2025/06/c328da14bbb15fc4ad571dc33e7a4ab3.pdf"
    document_title: "THE CODE ON WAGES, 2019"
    document_type: "Act"
    issuing_authority: "Ministry of Law and Justice, Legislative Department"
    date: 2019-01-01
    domain: "labour"