"""add unique constraints

Revision ID: 2e76f1ae36a3
Revises: 042b6116455d
Create Date: 2026-07-02 20:02:19.677134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e76f1ae36a3'
down_revision: Union[str, Sequence[str], None] = '042b6116455d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_chunk', 'document_chunks', ['domain', 'source', 'content'])
    op.create_unique_constraint('uq_message_turn', 'messages', ['conversation_id', 'turn_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_message_turn', 'messages', type_='unique')
    op.drop_constraint('uq_document_chunk', 'document_chunks', type_='unique')
    # ### end Alembic commands ###
