"""add legal chunk model

Revision ID: 6a8fa7c7de33
Revises: 57723bdc0e49
Create Date: 2026-07-13 02:24:32.888149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector,VECTOR
# revision identifiers, used by Alembic.
revision: str = '6a8fa7c7de33'
down_revision: Union[str, Sequence[str], None] = '57723bdc0e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', VECTOR(dim=1024), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_legal_chunk_metadata_gin', 'legal_chunks', ['chunk_metadata'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_legal_chunk_metadata_gin', table_name='legal_chunks', postgresql_using='gin')
    op.drop_table('legal_chunks')
    # ### end Alembic commands ###
