"""Test Migrate

Revision ID: fd653ea4cc65
Revises: 293d31542c17
Create Date: 2026-07-17 20:43:52.038248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd653ea4cc65'
down_revision: Union[str, Sequence[str], None] = '293d31542c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('domain', sa.Text(), nullable=False))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'domain')
    # ### end Alembic commands ###
